CRITICAL - 2022-04-28 21:55:29 --> Invalid file: departure_detail_add.php
#0 C:\xampp\htdocs\prueba\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('departure_detai...')
#1 C:\xampp\htdocs\prueba\system\Common.php(1089): CodeIgniter\View\View->render('departure_detai...', Array, true)
#2 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(38): view('departure_detai...')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->add_detail()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 21:55:35 --> Invalid file: departure_detail_add.php
#0 C:\xampp\htdocs\prueba\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('departure_detai...')
#1 C:\xampp\htdocs\prueba\system\Common.php(1089): CodeIgniter\View\View->render('departure_detai...', Array, true)
#2 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(38): view('departure_detai...')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->add_detail()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:05:39 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(65): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 65)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->state_delivered()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:06:28 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(65): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->state_delivered()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:07:07 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(65): redirect('http://localhos...')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->state_delivered()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:10:29 --> CodeIgniter\HTTP\RedirectResponse::to(): Argument #2 ($code) must be of type ?int, string given, called in C:\xampp\htdocs\prueba\app\Controllers\Departure.php on line 65
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(65): CodeIgniter\HTTP\RedirectResponse->to('http://localhos...', 'refresh')
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->state_delivered()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:10:52 --> 1 is not a valid HTTP return status code
#0 C:\xampp\htdocs\prueba\system\HTTP\ResponseTrait.php(151): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidStatusCode(1)
#1 C:\xampp\htdocs\prueba\system\HTTP\ResponseTrait.php(528): CodeIgniter\HTTP\Response->setStatusCode(1)
#2 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(40): CodeIgniter\HTTP\Response->redirect('http://localhos...', 'refresh', 1)
#3 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(65): CodeIgniter\HTTP\RedirectResponse->to('http://localhos...', 1, 'refresh')
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->state_delivered()
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#6 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-04-28 23:11:07 --> syntax error, unexpected double-quoted string "refresh", expecting ")"
#0 C:\xampp\htdocs\prueba\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('departure/state...')
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('departure/state...')
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:40:34 --> syntax error, unexpected token "}"
#0 C:\xampp\htdocs\prueba\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute('home/login_vali...')
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(726): CodeIgniter\Router\Router->handle('home/login_vali...')
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:41:13 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:37 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:37 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:38 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:38 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:38 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:38 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:38 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:39 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:41:49 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:42:09 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(25): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:42:10 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(25): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:42:11 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(25): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:42:11 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(25): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:42:57 -->  route cannot be found while reverse-routing.
#0 C:\xampp\htdocs\prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\prueba\system\Common.php(832): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\prueba\app\Controllers\Home.php(24): redirect('http://localhos...', 'refresh')
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Home->login_validate()
#4 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-04-28 23:46:05 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->index()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:53:40 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->index()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:53:41 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->index()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:53:42 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->index()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:53:42 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->index()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:53:43 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->index()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-04-28 23:53:43 --> Undefined property: App\Controllers\Departure::$load
#0 C:\xampp\htdocs\prueba\app\Controllers\Departure.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 9)
#1 C:\xampp\htdocs\prueba\system\CodeIgniter.php(832): App\Controllers\Departure->index()
#2 C:\xampp\htdocs\prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Departure))
#3 C:\xampp\htdocs\prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
